import java.lang.reflect.Array;
import java.util.ArrayDeque;
import java.util.ArrayList;

public class TweetClass {
    public static boolean contains(String word,String Tweet){
        if( Tweet.contains(word)){
            return true;
        }
        else{
            return false;
        }
    }

    public static void main(String[] args){
        ArrayList<String> tweets = new ArrayList<String>();
        tweets.add(0,"It is now possible to learn about a person's mobility preferences from data generated by their smartphone");
        tweets.add(1,"someperson");
        //TheTweeter tweetRunner = new TheTweeter();

        System.out.println(contains("b",tweets.get(0)));
    }
}
